# LFXO configuration for the nrf5340dk/nrf5340/cpuapp sysbuild image.
# Keep this aligned with the network-core transmitter image.
CONFIG_SOC_ENABLE_LFXO=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_SOC_LFXO_CAP_EXTERNAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_20PPM=y
CONFIG_SOC_LFXO_BYPASS=y

CONFIG_SOC_HFXO_CAP_INTERNAL=y
CONFIG_SOC_HFXO_CAP_INT_VALUE_X2=25