if(NOT DEFINED MSENSE_SOURCE_ROOT OR MSENSE_SOURCE_ROOT STREQUAL "")
	message(FATAL_ERROR "MSENSE_SOURCE_ROOT must identify the repository root")
endif()

if(NOT DEFINED MSENSE_PRODUCT OR
	   (NOT MSENSE_PRODUCT STREQUAL "PPGv2" AND NOT MSENSE_PRODUCT STREQUAL "ECGv0"))
	message(FATAL_ERROR "MSENSE_PRODUCT must be PPGv2 or ECGv0")
endif()

if(NOT DEFINED MSENSE_APP_BUILD_DIR OR MSENSE_APP_BUILD_DIR STREQUAL "")
	message(FATAL_ERROR "MSENSE_APP_BUILD_DIR must identify the application child build")
endif()

function(require_text relative_path required_text)
	set(source_path "${MSENSE_SOURCE_ROOT}/${relative_path}")

	if(NOT EXISTS "${source_path}")
		message(FATAL_ERROR "Required source file is missing: ${relative_path}")
	endif()

	file(READ "${source_path}" source_contents)
	string(FIND "${source_contents}" "${required_text}" required_position)
	if(required_position EQUAL -1)
		message(FATAL_ERROR
			"${relative_path} no longer contains the required Phase 4 contract: ${required_text}")
	endif()
endfunction()

function(require_absent relative_path)
	if(EXISTS "${MSENSE_SOURCE_ROOT}/${relative_path}")
		message(FATAL_ERROR "Forbidden Phase 4 compatibility path is present: ${relative_path}")
	endif()
endfunction()

function(require_text_absent relative_path forbidden_text)
	set(source_path "${MSENSE_SOURCE_ROOT}/${relative_path}")

	if(NOT EXISTS "${source_path}")
		message(FATAL_ERROR "Required source file is missing: ${relative_path}")
	endif()

	file(READ "${source_path}" source_contents)
	string(FIND "${source_contents}" "${forbidden_text}" forbidden_position)
	if(NOT forbidden_position EQUAL -1)
		message(FATAL_ERROR
			"${relative_path} contains forbidden Phase 4 compatibility text: ${forbidden_text}")
	endif()
endfunction()

function(require_file file_path)
	if(NOT EXISTS "${file_path}")
		message(FATAL_ERROR "Expected sysbuild artifact is missing: ${file_path}")
	endif()
endfunction()

function(require_config config_path required_text)
	if(NOT EXISTS "${config_path}")
		message(FATAL_ERROR "Expected generated configuration is missing: ${config_path}")
	endif()

	file(READ "${config_path}" config_contents)
	string(FIND "${config_contents}" "${required_text}" required_position)
	if(required_position EQUAL -1)
		message(FATAL_ERROR
			"${config_path} no longer contains the required Phase 4 setting: ${required_text}")
	endif()
endfunction()

require_text("shared/CMakeLists.txt"
	"zephyr_library_sources_ifdef(CONFIG_USB_MASS_STORAGE msc_media.c)")
require_text("PPGv2/CMakeLists.txt" "project(PPGv2)")
require_text("ECGv0/CMakeLists.txt" "project(ECGv0)")
require_text_absent("PPGv2/CMakeLists.txt" "project(MotionSenseHrv)")
require_text_absent("ECGv0/CMakeLists.txt" "project(MotionSenseHrv)")
require_text("PPGv2/CMakeLists.txt" "msense_add_git_metadata")
require_text("ECGv0/CMakeLists.txt" "msense_add_git_metadata")
require_text("shared/cmake/msense_sysbuild.cmake" "if(SB_CONFIG_NETCORE_HCI_IPC)")
require_text("shared/cmake/msense_sysbuild.cmake" "add_overlay_config(hci_ipc")
require_text("PPGv2/sysbuild.cmake" "shared/cmake/msense_sysbuild.cmake")
require_text("ECGv0/sysbuild.cmake" "shared/cmake/msense_sysbuild.cmake")
require_text("PPGv2/sysbuild.cmake" "child_image/hci_ipc.conf")
require_text("ECGv0/sysbuild.cmake" "child_image/hci_ipc.conf")
require_text("PPGv2/src/zephyrfilesystem.c" "uuid.txt")
require_text("ECGv0/src/zephyrfilesystem.c" "uuid.txt")
require_text("PPGv2/src/zephyrfilesystem.c" "Git Commit: %s\\nGit Tree: %s")
require_text("ECGv0/src/zephyrfilesystem.c" "Git Commit: %s\\nGit Tree: %s")
require_text("PPGv2/src/main.c" "msense_msc_media_publish_to_host")
require_text("ECGv0/src/main.c" "msense_msc_media_publish_to_host")
require_text("PPGv2/src/main.c" "msense_device_identity_model")
require_text("ECGv0/src/main.c" "msense_device_identity_model")

require_absent("ECGv0/src/ble_ppg_compat.c")
require_absent("ECGv0/src/ppgSensor.c")

get_filename_component(msense_build_root "${MSENSE_APP_BUILD_DIR}" DIRECTORY)
set(app_config "${MSENSE_APP_BUILD_DIR}/zephyr/.config")
set(app_cache "${MSENSE_APP_BUILD_DIR}/CMakeCache.txt")
set(hci_config "${msense_build_root}/hci_ipc/zephyr/.config")
set(metadata_header "${MSENSE_APP_BUILD_DIR}/generated/msense_git_metadata.h")

require_file("${MSENSE_APP_BUILD_DIR}/zephyr/zephyr.elf")
require_file("${MSENSE_APP_BUILD_DIR}/zephyr/zephyr.hex")
require_file("${msense_build_root}/mcuboot/zephyr/zephyr.hex")
require_file("${msense_build_root}/hci_ipc/zephyr/zephyr.hex")
require_file("${msense_build_root}/merged.hex")
require_config("${app_config}" "CONFIG_BOOTLOADER_MCUBOOT=y")
require_config("${metadata_header}" "#define MSENSE_GIT_COMMIT \"")
require_config("${app_cache}" "CMAKE_PROJECT_NAME:STATIC=${MSENSE_PRODUCT}")

if(MSENSE_PRODUCT STREQUAL "PPGv2")
	require_config("${app_cache}" "BOARD:STRING=ppgv2/nrf5340/cpuapp")
	require_text("PPGv2/src/main.c" "#define MSENSE_PRODUCT_BLE_NAME_PREFIX \"MSense4PPG-\"")
	require_text("PPGv2/prj.conf" "CONFIG_BT_DEVICE_NAME=\"MSense4PPG-\"")
	require_text("PPGv2/prj.conf" "CONFIG_BT_DIS_MODEL=\"5.1.4 UProd\"")
	require_text("PPGv2/src/BLEService.h" "#define PPG_TX_CHARACTERISTIC_UUID")
	require_text("PPGv2/src/BLEService.h" "0x1D, 0x20, 0xC9, 0x39, 0xDA")
	require_text("PPGv2/src/BLEService.h" "0x1D, 0x23, 0xC9, 0x39, 0xDA")
	require_text("PPGv2/src/BLEService.h" "0x1D, 0x24, 0xC9, 0x39, 0xDA")
	require_text("PPGv2/src/BLEService.c" "BT_GATT_SERVICE_DEFINE(data_service")
	require_text("PPGv2/CMakeLists.txt" "src/ppgSensor.c")
	require_text("PPGv2/src/imuSensor.c" "imuSensor")
	require_absent("PPGv2/src/ship_mode.c")
	require_text_absent("PPGv2/src/main.c" "SHIP_MODE_")
	require_text_absent("boards/senselab/ppgv2/ppgv2_nrf5340_cpuapp.dts" "user-button =")
	require_config("${app_config}" "CONFIG_SOC_LFXO_CAP_INT_9PF=y")
	require_config("${app_config}" "# CONFIG_SOC_LFXO_BYPASS is not set")
	require_config("${hci_config}" "CONFIG_BT_CTLR_TX_PWR_PLUS_3=y")
else()
	require_config("${app_cache}" "BOARD:STRING=ecgv0/nrf5340/cpuapp")
	require_text("ECGv0/src/main.c" "#define MSENSE_PRODUCT_BLE_NAME_PREFIX \"MSense4ECG-\"")
	require_text("ECGv0/prj.conf" "CONFIG_BT_DEVICE_NAME=\"MSense4ECG-\"")
	require_text("ECGv0/prj.conf" "CONFIG_BT_DIS_MODEL=\"5.0.2 NAND\"")
	require_text("ECGv0/src/BLEService.h" "#define TIMING_UPDATE_SERVICE_UUID")
	require_text("ECGv0/src/BLEService.h" "0x1D, 0x50, 0xC9, 0x39, 0xDA")
	require_text("ECGv0/src/BLEService.h" "0x1D, 0x51, 0xC9, 0x39, 0xDA")
	require_text("ECGv0/src/BLEService.c" "BT_GATT_SERVICE_DEFINE(timing_update_service")
	require_text("ECGv0/CMakeLists.txt" "src/drivers/ecg/max30001.c")
	require_text("ECGv0/src/icm20948_accel.c" "icm20948")
	require_text("ECGv0/src/main.c" "SHIP_MODE_WAITING_FOR_BUTTON")
	require_text("boards/senselab/ecgv0/ecgv0_nrf5340_cpuapp.dts" "user-button = &button0")
	require_text_absent("ECGv0/CMakeLists.txt" "src/ppgSensor.c")
	require_text_absent("ECGv0/src/BLEService.h" "PPG_TX_CHARACTERISTIC_UUID")
	require_config("${app_config}" "CONFIG_SOC_LFXO_BYPASS=y")
	require_config("${app_config}" "CONFIG_SOC_LFXO_CAP_EXTERNAL=y")
	require_config("${hci_config}" "CONFIG_BT_CTLR_TX_PWR_0=y")
	require_config("${hci_config}" "CONFIG_BT_CTLR_PHY_2M=y")
	require_config("${hci_config}" "CONFIG_BT_CTLR_PHY_CODED=y")
endif()
