/*
 * Copyright (c) 2026 The Ohio State University SENSE Lab
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef MSENSE_SENSOR_STREAM_PROTOCOL_H_
#define MSENSE_SENSOR_STREAM_PROTOCOL_H_

#include <stdint.h>

/* Transport version is independent of each product's binary record format. */
#define MSENSE_SENSOR_STREAM_PROTOCOL_VERSION 0U
#define MSENSE_SENSOR_STREAM_PROTOCOL_VERSION_PPG MSENSE_SENSOR_STREAM_PROTOCOL_VERSION
#define MSENSE_SENSOR_STREAM_PROTOCOL_VERSION_ECG MSENSE_SENSOR_STREAM_PROTOCOL_VERSION
#define MSENSE_SENSOR_STREAM_MAGIC0 0x4DU
#define MSENSE_SENSOR_STREAM_MAGIC1 0x53U

#define MSENSE_SENSOR_STREAM_COMMAND_BYTES 8U
#define MSENSE_SENSOR_STREAM_HEADER_BYTES 12U
#define MSENSE_SENSOR_STREAM_START_ACK_BYTES 16U
#define MSENSE_SENSOR_STREAM_DATA_PREFIX_BYTES 8U
#define MSENSE_SENSOR_STREAM_RESULT_BYTES 2U
#define MSENSE_SENSOR_STREAM_END_BYTES 2U
/* ACK history count is in 4096-byte units, not product records. */
#define MSENSE_SENSOR_STREAM_HISTORY_UNITS 8U
#define MSENSE_SENSOR_STREAM_HISTORY_BYTES 32768U
#define MSENSE_SENSOR_STREAM_FINITE_BYTES 131072U

#define MSENSE_SENSOR_STREAM_OPCODE_START 0x01U
#define MSENSE_SENSOR_STREAM_OPCODE_STOP 0x02U
#define MSENSE_SENSOR_STREAM_OPCODE_START_INFINITY 0x03U
#define MSENSE_SENSOR_STREAM_OPCODE_CANCEL MSENSE_SENSOR_STREAM_OPCODE_STOP

#define MSENSE_SENSOR_STREAM_MESSAGE_START_ACK 0x81U
#define MSENSE_SENSOR_STREAM_MESSAGE_DATA 0x82U
#define MSENSE_SENSOR_STREAM_MESSAGE_END 0x83U
#define MSENSE_SENSOR_STREAM_MESSAGE_RESULT 0x84U

#define MSENSE_SENSOR_STREAM_PPG_RECORD_SIZE 16U
#define MSENSE_SENSOR_STREAM_PPG_HISTORY_RECORDS 2048U
#define MSENSE_SENSOR_STREAM_PPG_FORWARD_RECORDS 6144U
#define MSENSE_SENSOR_STREAM_PPG_TOTAL_SENSOR_BYTES 131072U

#define MSENSE_SENSOR_STREAM_ECG_RECORD_SIZE 4096U
#define MSENSE_SENSOR_STREAM_ECG_HISTORY_RECORDS 8U
#define MSENSE_SENSOR_STREAM_ECG_FORWARD_RECORDS 24U
#define MSENSE_SENSOR_STREAM_ECG_TOTAL_SENSOR_BYTES 131072U

/* Shared code reserves enough RAM for the larger whole-record payload. */
#define MSENSE_SENSOR_STREAM_CAPTURE_BUFFER_BYTES \
	MSENSE_SENSOR_STREAM_ECG_TOTAL_SENSOR_BYTES

enum msense_sensor_stream_device_type {
	MSENSE_SENSOR_STREAM_DEVICE_PPG = 0x01,
	MSENSE_SENSOR_STREAM_DEVICE_ECG = 0x02,
};

enum msense_sensor_stream_status {
	MSENSE_SENSOR_STREAM_STATUS_SUCCESS = 0x0000,
	MSENSE_SENSOR_STREAM_STATUS_NOT_RECORDING = 0x0001,
	MSENSE_SENSOR_STREAM_STATUS_HISTORY_NOT_READY = 0x0002,
	MSENSE_SENSOR_STREAM_STATUS_NOT_SUBSCRIBED = 0x0003,
	MSENSE_SENSOR_STREAM_STATUS_BUSY = 0x0004,
	MSENSE_SENSOR_STREAM_STATUS_MTU_TOO_SMALL = 0x0005,
	MSENSE_SENSOR_STREAM_STATUS_INVALID_COMMAND = 0x0006,
	MSENSE_SENSOR_STREAM_STATUS_UNSUPPORTED_VERSION = 0x0007,
	MSENSE_SENSOR_STREAM_STATUS_CANCELLED = 0x0008,
	MSENSE_SENSOR_STREAM_STATUS_STORAGE_ERROR = 0x0009,
	MSENSE_SENSOR_STREAM_STATUS_INTERNAL_ERROR = 0x000A,
	MSENSE_SENSOR_STREAM_STATUS_NOT_INITIALIZED = 0x000B,
	MSENSE_SENSOR_STREAM_STATUS_WRONG_SESSION = 0x000C,
	MSENSE_SENSOR_STREAM_STATUS_DISCONNECTED = 0x000D,
	MSENSE_SENSOR_STREAM_STATUS_BUFFER_OVERFLOW = 0x000E,
};

#define MSENSE_SENSOR_STREAM_STATUS_STOPPED MSENSE_SENSOR_STREAM_STATUS_CANCELLED

#endif /* MSENSE_SENSOR_STREAM_PROTOCOL_H_ */
