#ifndef MSENSE_FATAL_RETENTION_H_
#define MSENSE_FATAL_RETENTION_H_

#include <zephyr/toolchain.h>

enum msense_fatal_stage {
	MSENSE_FATAL_STAGE_BOOT = 0,
	MSENSE_FATAL_STAGE_COLLECTION_REQUEST,
	MSENSE_FATAL_STAGE_COLLECTION_ENTER,
	MSENSE_FATAL_STAGE_STORAGE_MOUNT,
	MSENSE_FATAL_STAGE_RTC_START,
	MSENSE_FATAL_STAGE_ECG_START,
	MSENSE_FATAL_STAGE_ACCEL_START,
	MSENSE_FATAL_STAGE_IMU_START,
	MSENSE_FATAL_STAGE_FSYNC_START,
	MSENSE_FATAL_STAGE_BLE_TIMING_START,
	MSENSE_FATAL_STAGE_COLLECTION_READY,
	MSENSE_FATAL_STAGE_PPG_START,
};

void msense_fatal_stage_set(enum msense_fatal_stage stage);
void msense_fatal_retention_report(void);
FUNC_NORETURN void msense_normal_reset(void);

#endif
